[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Inflation multipler

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "self.extra_cost = 0 + G.GAME.inflation"
position = "at"
payload = '''
self.extra_cost = (0 + G.GAME.inflation) * G.GAME.xinflation
'''
match_indent = true
