[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = "if obj and obj.remove_from_deck and type(obj.remove_from_deck) == 'function' then"
position = "at"
payload = '''
if obj and obj.remove_from_deck and type(obj.remove_from_deck) == 'function' and not RevosVault.remove_lock then
'''
match_indent = true 