[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

# shuffle 'em all

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''
local text,disp_text,poker_hands,scoring_hand,non_loc_disp_text = G.FUNCS.get_poker_hand_info(G.play.cards)'''
position = 'before'
payload = '''
-- pseudoshuffle(G.play.cards)
SMODS.calculate_context({crv_before_before = true})
'''
match_indent = true